Add A Grade
htjahyon/student-grade-table pull request #3
Opened 2020-11-27 23:41 UTC by htjahyon

![image](https://user-images.githubusercontent.com/68126492/100489062-e2b36e80-30c6-11eb-8231-dd7ecaa9b5e8.png)

2020-11-30 20:06 UTC, TimelikeClosure requested changes

2020-11-30 20:06 UTC, TimelikeClosure commented on index.html
> +            <input type="grade" class="form-control" id="grade1" value="Grade">
All `<input>`s inside a `<form>` need a `name` attribute, otherwise their `value`s won't be included when the `<form>` submits:

---

![Screenshot_6](https://user-images.githubusercontent.com/16143771/100655460-2a710a80-3300-11eb-988c-a9992f99f9a7.jpg)

2020-11-30 20:06 UTC, TimelikeClosure commented on index.html
> +            <input type="grade" class="form-control" id="grade1" value="Grade">
Missing `name` attributes also mean you won't be able to `get` the `value`s out of a `FormData` object, since its `get` method looks `value`s up by `name`.

---

![Screenshot_7](https://user-images.githubusercontent.com/16143771/100655627-6a37f200-3300-11eb-8a9d-88ca3f95f5bc.jpg)

---

![Screenshot_8](https://user-images.githubusercontent.com/16143771/100655699-80de4900-3300-11eb-9c76-bce64ca3d299.jpg)

2020-11-30 20:06 UTC, TimelikeClosure commented on components/grade-form.js
> +    var grade = document.querySelector("#grade1").value;
`get`ting `value`s from a `FormData` object should work after adding `name`s to the relevant `<input>`s.

2020-11-30 20:06 UTC, TimelikeClosure commented on components/grade-form.js
> +    var grade = document.querySelector("#grade1").value;
However, in event listener callbacks, start with the `target` property of the `event` object instead of querying the entire `document`: its less prone to breaking with changes to the DOM, and it's a lot less work for the JS engine.

2020-11-30 20:06 UTC, TimelikeClosure commented on components/app.js
> +    console.log("Error Dude!");
Just pass the `String` to the `error` method. There's no reason to also call the `log` method here.

2020-11-30 20:06 UTC, TimelikeClosure commented on components/app.js
> +  }
In general, you should describe _what_ the error is for. As your applications get more complicated, it'll make the source of errors a whole lot simpler to chase down.

For example, seeing one of these in your console:

---

![Screenshot_14](https://user-images.githubusercontent.com/16143771/100658359-c3555500-3303-11eb-914e-d7c4c82d6c83.jpg)

![Screenshot_15](https://user-images.githubusercontent.com/16143771/100658549-17f8d000-3304-11eb-8624-639b32bd463a.jpg)

---

gives you a much better idea of where to start debugging than seeing this:

---

![Screenshot_10](https://user-images.githubusercontent.com/16143771/100657683-2db9c580-3303-11eb-8ea9-c3a09e883be6.jpg)

2020-12-02 04:41 UTC, htjahyon commented
![image](https://user-images.githubusercontent.com/68126492/100829158-9002eb00-3415-11eb-96c2-10c9fb54b854.png)

2020-12-02 04:48 UTC, TimelikeClosure commented on components/grade-table.js
> +    }
- You don't need to query the `"dataRow"` class elements. Just call `remove` on the `childNodes` directly:
    ```js
    tbodyElement.childNodes[j].remove();
    ```
- The `length` of `childNodes` gets shorter by one every time you `remove` a child node, which means you'll skip nodes if you iterate over it forward.

2020-12-02 05:06 UTC, htjahyon commented
![image](https://user-images.githubusercontent.com/68126492/100830720-22f15480-3419-11eb-904c-811f7e9e2342.png)

2020-12-02 05:11 UTC, TimelikeClosure approved these changes

2020-12-02 05:16 UTC, merged